### ISSUE TITLE
Problem compiling for LED_STRIP_SM16703

### ISSUE THREAD

**Issue by ahmetcemturan** [Xylopyrographer/LiteLED#7]
Hi,
I am trying to get Blink example to run with IC16703 but I can't compile.
I get this error:
\LiteLED\src/LiteLED.h:11:10: fatal error: hal/rmt_types.h: No such file or directory
   11 | #include <hal/rmt_types.h>
I tried to comment out this include and basically all includes on that page fail....

#include <hal/rmt_types.h>
#include <driver/gpio.h>
#include <esp_err.h>
#include <driver/rmt.h>
#include "llrgb.h"

I would really like to try out your driver as the FastLED is failing me with 16703.

Ah well I just noticed that it is for ESP32... :(    Do You plan on porting it for ESP8266?

**Comment by Xylopyrographer** [comment]
Hi. Could you let me know your development environment? Which IDE, which version, which esp32 version you're trying to run it on, and most importantly - which version of the Arduino-esp32 core are you using?

Note that LiteLED does not work with Arduino-esp32 core versions 3.x.x. Latest tested core version is v2.0.14, though I'm sure it would work with 2.0.16 as well (don't use 2.0.15).

**Comment by ahmetcemturan** [comment]
I was trying to run it on an ESP07  (Wemos D1 Mini) :(

**Comment by Xylopyrographer** [comment]
Hi. The LiteLED library depends on the RMT peripheral of the ESP32 series chips. As the ESP-8266EX doesn’t have an RMT, it is not possible to port to that chip.

Hope you find a solution.
